### ISSUE TITLE
编译部署需要上传哪些文件

### ISSUE THREAD

**Issue by imhazige** [easy-team/egg-vue-webpack-boilerplate#122]
很好的工具。
编译部署的文档能不能写写。
我想知道：
`npm run build`之后。哪些文件是最终产生的上传到服务器可以运行的文件？我不可能把整个项目源码传上去吧。

**Comment by hubcarl** [comment]
@imhazige  见 https://www.yuque.com/easy-team/egg-vue/online

**Comment by kongbingzhe** [comment]
```
mport ListView from '../page/list';

import DetailView from '../page/detail.vue';

Vue.use(VueRouter);

export default function createRouter(initState, options) {
  const { base } = options;
  return new VueRouter({
    mode: 'history',
    base,
    routes: [
      {
        path: '/',
        component: ListView
      },
      {
        path: '/list/:id',
        component: ListView
      },
      {
        path: '/detail/:id',
        component: () => import('../page/detail.vue')
      }
    ]
  });
}
```

```
import { SET_ARTICLE_LIST, SET_ARTICLE_DETAIL } from '../type';
import axios from 'axios';

export default initState => {
  const name = 'article';
  const preState = initState[name];
  let state = {
    articleList: [],
    articleItem: {}
  };
  if (preState) {
    state = { ...state, ...preState };
  }
  const actions = {
    FETCH_ARTICLE_LIST: ({ commit, dispatch, rootState, state }) => {
      if (!state.articleList.length) {
        return axios
          .get(`${rootState.origin}/spa/api/article/list`)
          .then(response => {
            commit(SET_ARTICLE_LIST, response.data.list);
          });
      }
    },

    FETCH_ARTICLE_DETAIL: ({ commit, dispatch, rootState, state }, { id }) => {
      console.log(444444);
      if (state.articleItem.id !== Number(id)) {
        return axios
          .get(`${rootState.origin}/spa/api/article/${id}`)
          .then(response => {
            commit(SET_ARTICLE_DETAIL, response.data);
          });
      }
    }
  };
  const mutations = {
    [SET_ARTICLE_LIST](state, items) {
      state.articleList = items;
    },
    [SET_ARTICLE_DETAIL](state, data) {
      state.articleItem = { ...state.articleItem, ...data };
    }
  };

  return {
    state,
    actions,
    mutations
  };
};

```
报错： vue.runtime.common.dev.js:621 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
warn @ vue.runtime.common.dev.js:621
patch @ vue.runtime.common.dev.js:6475
Vue._update @ vue.runtime.common.dev.js:3933
updateComponent @ vue.runtime.common.dev.js:4054
get @ vue.runtime.common.dev.js:4465
Watcher @ vue.runtime.common.dev.js:4454
mountComponent @ vue.runtime.common.dev.js:4061
Vue.$mount @ vue.runtime.common.dev.js:8392
init @ vue.runtime.common.dev.js:3112
hydrate @ vue.runtime.common.dev.js:6358
hydrate @ vue.runtime.common.dev.js:6390
hydrate @ vue.runtime.common.dev.js:6390
hydrate @ vue.runtime.common.dev.js:6390
hydrate @ vue.runtime.common.dev.js:6390
patch @ vue.runtime.common.dev.js:6471
Vue._update @ vue.runtime.common.dev.js:3933
updateComponent @ vue.runtime.common.dev.js:4054
get @ vue.runtime.common.dev.js:4465
Watcher @ vue.runtime.common.dev.js:4454
mountComponent @ vue.runtime.common.dev.js:4061
Vue.$mount @ vue.runtime.common.dev.js:8392
init @ vue.runtime.common.dev.js:3112
hydrate @ vue.runtime.common.dev.js:6358
hydrate @ vue.runtime.common.dev.js:6390
patch @ vue.runtime.common.dev.js:6471
Vue._update @ vue.runtime.common.dev.js:3933
updateComponent @ vue.runtime.common.dev.js:4054
get @ vue.runtime.common.dev.js:4465
Watcher @ vue.runtime.common.dev.js:4454
mountComponent @ vue.runtime.common.dev.js:4061
Vue.$mount @ vue.runtime.common.dev.js:8392
init @ vue.runtime.common.dev.js:3112
hydrate @ vue.runtime.common.dev.js:6358
hydrate @ vue.runtime.common.dev.js:6390
patch @ vue.runtime.common.dev.js:6471
Vue._update @ vue.runtime.common.dev.js:3933
updateComponent @ vue.runtime.common.dev.js:4054
get @ vue.runtime.common.dev.js:4465
Watcher @ vue.runtime.common.dev.js:4454
mountComponent @ vue.runtime.common.dev.js:4061
Vue.$mount @ vue.runtime.common.dev.js:8392
init @ vue.runtime.common.dev.js:3112
hydrate @ vue.runtime.common.dev.js:6358
patch @ vue.runtime.common.dev.js:6471
Vue._update @ vue.runtime.common.dev.js:3933
updateComponent @ vue.runtime.common.dev.js:4054
get @ vue.runtime.common.dev.js:4465
Watcher @ vue.runtime.common.dev.js:4454
mountComponent @ vue.runtime.common.dev.js:4061
Vue.$mount @ vue.runtime.common.dev.js:8392
client @ app.js:76
bootstrap @ app.js:35
eval @ index.js:23
./web/framework/index.js @ app.js:127
__webpack_require__ @ runtime.js:33
checkDeferredModulesImpl @ runtime.js:1168
webpackJsonpCallback @ runtime.js:1150
(anonymous) @ app.js:9
Show 28 more frames
app.js:65 

如何进行store的拆分，我拆分之后，发现路由懒加载的组件会报错，非懒加载的路由组件正常
